# # This is a basic workflow to help you get started with Actions
name: Deploy Azure Resources
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Script
        run: echo Starting Bicep...
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Deploy the Bicep Script
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "rg-bicep-asolom"
          template: azure-resources.bicep
